
package eu.ensup.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrackServiceService", targetNamespace = "http://service.ensup.eu/", wsdlLocation = "http://192.168.133.19:8888/track?wsdl")
public class TrackServiceService
    extends Service
{

    private final static URL TRACKSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TRACKSERVICESERVICE_EXCEPTION;
    private final static QName TRACKSERVICESERVICE_QNAME = new QName("http://service.ensup.eu/", "TrackServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.133.19:8888/track?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRACKSERVICESERVICE_WSDL_LOCATION = url;
        TRACKSERVICESERVICE_EXCEPTION = e;
    }

    public TrackServiceService() {
        super(__getWsdlLocation(), TRACKSERVICESERVICE_QNAME);
    }

    public TrackServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRACKSERVICESERVICE_QNAME, features);
    }

    public TrackServiceService(URL wsdlLocation) {
        super(wsdlLocation, TRACKSERVICESERVICE_QNAME);
    }

    public TrackServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRACKSERVICESERVICE_QNAME, features);
    }

    public TrackServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrackServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrackService
     */
    @WebEndpoint(name = "TrackServicePort")
    public TrackService getTrackServicePort() {
        return super.getPort(new QName("http://service.ensup.eu/", "TrackServicePort"), TrackService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrackService
     */
    @WebEndpoint(name = "TrackServicePort")
    public TrackService getTrackServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ensup.eu/", "TrackServicePort"), TrackService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRACKSERVICESERVICE_EXCEPTION!= null) {
            throw TRACKSERVICESERVICE_EXCEPTION;
        }
        return TRACKSERVICESERVICE_WSDL_LOCATION;
    }

}
