openapi: 3.0.1

paths:
  /track/sandman:
    get:
      operationId: getTrackInJson
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
  /track:
    post:
      operationId: createTrackInJson
      requestBody:
        description: Track is the best
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Track'
      responses:
        default:
          description: default response
          content:
            application/json: {}
components:
  schemas:
    Track:
      type: object
      properties:
        title:
          type: string
        singer:
          type: string
      xml:
        name: Track
