
package eu.ensup.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrackWSService", targetNamespace = "http://service.ensup.eu/", wsdlLocation = "http://localhost:8080/SOAPServer/track?wsdl")
public class TrackWSService
    extends Service
{

    private final static URL TRACKWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRACKWSSERVICE_EXCEPTION;
    private final static QName TRACKWSSERVICE_QNAME = new QName("http://service.ensup.eu/", "TrackWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAPServer/track?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRACKWSSERVICE_WSDL_LOCATION = url;
        TRACKWSSERVICE_EXCEPTION = e;
    }

    public TrackWSService() {
        super(__getWsdlLocation(), TRACKWSSERVICE_QNAME);
    }

    public TrackWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRACKWSSERVICE_QNAME, features);
    }

    public TrackWSService(URL wsdlLocation) {
        super(wsdlLocation, TRACKWSSERVICE_QNAME);
    }

    public TrackWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRACKWSSERVICE_QNAME, features);
    }

    public TrackWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrackWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TrackWS
     */
    @WebEndpoint(name = "TrackWSPort")
    public TrackWS getTrackWSPort() {
        return super.getPort(new QName("http://service.ensup.eu/", "TrackWSPort"), TrackWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TrackWS
     */
    @WebEndpoint(name = "TrackWSPort")
    public TrackWS getTrackWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ensup.eu/", "TrackWSPort"), TrackWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRACKWSSERVICE_EXCEPTION!= null) {
            throw TRACKWSSERVICE_EXCEPTION;
        }
        return TRACKWSSERVICE_WSDL_LOCATION;
    }

}
